### PR TITLE
Configure subdir for generated images.

### PR DESCRIPTION
**Pull request by danylevskyi**
I'd like to propose to add a path for generated images in order to keep `images` directory clean and clear.

### CODE REVIEW

**Comment by danylevskyi** [comment]
Also, I've added relative_assets variable to make images (eg. sprites) wokring out of the box.

**Comment by konstantin-komelin** [comment]
Thanks for your pull request.

Could you please instruct me how to reproduce the situation when it's necessary?

**Comment by danylevskyi** [comment]
### Generated images.

Let's assume we have 6 social icons and we'd like to create a sprite using Compass. Without `generated_images_dir` we'll get new generated images like `social-s7444104aad.png` within `images` directory which is obviosly isn't clean solution. It's handy to have a separate dir which can be excluded with .gitignore later.

### Relative assets

Let's assume we are using next code to style aforementioned social icons:
```
@import "compass/utilities/sprites";
@import "social/*.png";
@include all-social-sprites();
```
In order to set proper paths to Drupal theme's assets we should set `relative_assets` to `true`.

**Comment by konstantin-komelin** [comment]
Thanks Dmytro for detailed instructions!
I agree, It's wise to have a separate image folder for all auto-generated sprites.
Give me some time to test your suggestions.

Best,
Konstantin

**Comment by kkomelin** [comment]
Good job. Thanks!

**Pull request merged**
